### ISSUE TITLE
homebridge config.json example please

### ISSUE THREAD

**Issue by ap91** [pumamood/homebridge-heatmiser#1]
Hi,
Please can you show an example of how to set out the config for the platform/accessories within the home bridge config file to register the thermostats?
Many thanks

**Comment by pumamood** [comment]
I've just updated readme with all details. Let me know if you need any other info.

**Comment by ap91** [comment]
Thank you. Where it says net monitor IP is that just the IP address for the thermostat?

On 18 Dec 2017, at 12:19, Puma <notifications@github.com<mailto:notifications@github.com>> wrote:


I've just updated readme with all details. Let me know if you need any other info.

-

**Comment by ap91** [comment]
Perfect - thank you for the prompt response/assistance. I would recommend updating the netmonitorip  commentary to be thermostat IP but not essential.

On a side note, one of the stats we're trialling this is a heating and hot water one but it errors on temperature read. I can post the debug log if it helps? But the others (normal WiFi ones heating only) work a treat

**Comment by Floppy** [comment]
@ap91 I'm getting an error with a HW stat when setting the temperature, which might be related. I've filed it in https://github.com/pumamood/homebridge-heatmiser/issues/2 - it would be helpful to know if your error is the same?
