### ISSUE TITLE
Error when setting temperature on PRTHW-TS WiFi RF

### ISSUE THREAD

**Issue by Floppy** [pumamood/homebridge-heatmiser#2]
Reading temperature works fine, but setting it results in:

```
[15/02/2019, 16:33:09] [Main Thermostat] getTemperatureDisplayUnits
[15/02/2019, 16:33:09] [Main Thermostat] getTemperatureDisplayUnits succeeded!
[15/02/2019, 16:33:09] [Main Thermostat] getCurrentTemperature
[15/02/2019, 16:33:10] [Main Thermostat] getCurrentTemperature succeeded!
[15/02/2019, 16:33:10] [Main Thermostat] getTargetHeatingCoolingState
[15/02/2019, 16:33:10] [Main Thermostat] getTargetHeatingCoolingState succeeded!
[15/02/2019, 16:33:14] [Main Thermostat] setTargetTemperature 23.2
/usr/local/lib/node_modules/homebridge-heatmiser/node_modules/heatmiser/lib/wifi.js:173
        this.emit('error', e);
             ^

TypeError: Cannot read property 'emit' of undefined
    at /usr/local/lib/node_modules/homebridge-heatmiser/node_modules/heatmiser/lib/wifi.js:173:14
    at Wifi.<anonymous> (/usr/local/lib/node_modules/homebridge-heatmiser/node_modules/heatmiser/lib/wifi.js:133:7)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
```

Running latest homebridge and heatmiser plugin on node 8.11.

**Comment by Floppy** [comment]
Ah! Looking at the `heatmiser` module, I see someone has reported this as a bug on there - looks like the model needs setting to an HW version. See https://github.com/carlossg/heatmiser-node/issues/3

**Comment by Floppy** [comment]
OK so I think what is needed is a model setting in the config, using the list at https://github.com/carlossg/heatmiser-node/blob/master/lib/wifi.js#L40. It's the fourth parameter to wifi.new, so it should be easy enough to pass in. I'll send a PR!

**Comment by pumamood** [comment]
Hi, i didn't have homebridge working anymore. I'll accept your PR, 'model' could be an optional paremeter for settings

**Comment by Floppy** [comment]
After a bit of experimentation, I've found that the heatmiser-node library configures itself for the right model without a problem, as long as you've read something from the stat before you try to write. Because the code in this module creates a new object each time it writes, the autoconfiguration doesn't work.

I can fix it without extra config by making the wifi object persistent, rather than recreated each time. This will also DRY up the code.

**Comment by Floppy** [comment]
Hm, https://github.com/carlossg/heatmiser-node/blob/master/lib/wifi.js#L167 should mean that the read-before-write isn't required, but it's not working for some reason.

(sorry for the stream of debugging notes, hope you don't mind @pumamood)

**Comment by Floppy** [comment]
I'm coming back to this now after having a break from homebridge; if I can get it working and debug my issues, I would be happy to take on maintenance of the plugin.

**Comment by iainbullock** [comment]
@Floppy I have the same problem with my PRTHW model. Did you ever get it to work?

**Comment by Floppy** [comment]
Turns out the pandemic is still going on and my life remains a mess, so no, not really. Also I'm playing with homeassistant now rather than homebridge; not that I've got that working either :)

**Comment by iainbullock** [comment]
Ok I understand. Good luck

Thanks for getting back to me

Iain

**Comment by pumamood** [comment]
hi guys you can PR what you need or became collaborator if you want

**Comment by iainbullock** [comment]
Hello I’m not planning to take this much further, just a few bug fixes and
tweaks maybe. Either way works for me. Thanks

**Comment by iainbullock** [comment]
@pumamood you can close this now
