### ISSUE TITLE
Heatmiser plug in not found

### ISSUE THREAD

**Issue by Fulltopuk** [pumamood/homebridge-heatmiser#3]
Hi

I know the was published two years ago but it is exactly what I was looking for.  Have loaded the Homebridge log is stating the error below. 

"Error: The requested accessory 'HeatmiserNetmonitor' was not registered by any plugin."

It seams to install ok so I am hoping the fix is simple.

Thanks

Richard

**Comment by pumamood** [comment]
Hi, I'm sorry but i don't have it installed anymore. I think it was tested in a previous release of homebridge and maybe it has to be adapted. I think you should check homebridge repository and maybe ask some forum with the error.

**Comment by Fulltopuk** [comment]
Hi. Thanks for the reply.

As a matter of interest what did you change your thermostat to?

Cheers

**Comment by oldscholar** [comment]
Hi.  I appreciate this is quite old now, but I'm interested where people got to with it.  I have a Heatmiser Netmonitor and 12v stats, which I want to link to Homebridge.  I would prefer not to have to replace all the kit to the Neo system, so I wondering what solutions others have found.  Have you replaced the system with Neo or some other solution, and if so what did you find?  Any help would be appreciated.  Thanks

**Comment by Fulltopuk** [comment]
Did not get anywhere.  I believe that if you have a netmonitor you cannot connect to it with more than one connection so I am thinking of maybe accessing through the webserver part instead.

**Comment by oldscholar** [comment]
Hi. Thanks for coming back to me. No, I haven’t managed to solve.  I hadn’t thought about the web server option, but I am a novice so not really sure where to start.  Any tips please?

**Comment by rilyas77** [comment]
Hi, I also have a netmonitor and 11 12v stats. I can access them from my Heatmiser app. Would like to know if any update on how to integrate this with HomeKit
